server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: springjpa-service
